namespace LethalSeedSimulator.Gui;

partial class Form1
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code

    private void InitializeComponent()
    {
        tabMain = new TabControl();
        tabInspect = new TabPage();
        btnInspect = new Button();
        txtInspectOutput = new TextBox();
        numInspectSeed = new NumericUpDown();
        labelInspectSeed = new Label();
        cmbInspectMoon = new ComboBox();
        labelInspectMoon = new Label();
        txtInspectVersion = new TextBox();
        labelInspectVersion = new Label();
        tabSearch = new TabPage();
        btnSearch = new Button();
        txtSearchOutput = new TextBox();
        txtSearchQuery = new TextBox();
        labelSearchQuery = new Label();
        numSearchEnd = new NumericUpDown();
        labelSearchEnd = new Label();
        numSearchStart = new NumericUpDown();
        labelSearchStart = new Label();
        cmbSearchMoon = new ComboBox();
        labelSearchMoon = new Label();
        txtSearchVersion = new TextBox();
        labelSearchVersion = new Label();
        tabExport = new TabPage();
        chkExportIncludeRollsJson = new CheckBox();
        btnCancelExport = new Button();
        btnBrowseExport = new Button();
        txtExportOutputFile = new TextBox();
        labelExportOutputFile = new Label();
        numExportReportInterval = new NumericUpDown();
        labelExportReportInterval = new Label();
        btnStartExport = new Button();
        txtExportLog = new TextBox();
        numExportEnd = new NumericUpDown();
        labelExportEnd = new Label();
        numExportStart = new NumericUpDown();
        labelExportStart = new Label();
        cmbExportMoon = new ComboBox();
        labelExportMoon = new Label();
        txtExportVersion = new TextBox();
        labelExportVersion = new Label();
        btnExtractRules = new Button();
        txtGlobalInfo = new TextBox();
        tabMain.SuspendLayout();
        tabInspect.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)numInspectSeed).BeginInit();
        tabSearch.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)numSearchEnd).BeginInit();
        ((System.ComponentModel.ISupportInitialize)numSearchStart).BeginInit();
        tabExport.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)numExportReportInterval).BeginInit();
        ((System.ComponentModel.ISupportInitialize)numExportEnd).BeginInit();
        ((System.ComponentModel.ISupportInitialize)numExportStart).BeginInit();
        this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        ClientSize = new Size(1180, 760);
        Controls.Add(txtGlobalInfo);
        Controls.Add(btnExtractRules);
        Controls.Add(tabMain);
        MinimumSize = new Size(1100, 700);
        Name = "Form1";
        Text = "Lethal Seed Simulator GUI";
        tabMain.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        tabMain.Controls.Add(tabInspect);
        tabMain.Controls.Add(tabSearch);
        tabMain.Controls.Add(tabExport);
        tabMain.Location = new Point(12, 74);
        tabMain.Name = "tabMain";
        tabMain.SelectedIndex = 0;
        tabMain.Size = new Size(1156, 674);
        tabInspect.Controls.Add(btnInspect);
        tabInspect.Controls.Add(txtInspectOutput);
        tabInspect.Controls.Add(numInspectSeed);
        tabInspect.Controls.Add(labelInspectSeed);
        tabInspect.Controls.Add(cmbInspectMoon);
        tabInspect.Controls.Add(labelInspectMoon);
        tabInspect.Controls.Add(txtInspectVersion);
        tabInspect.Controls.Add(labelInspectVersion);
        tabInspect.Location = new Point(4, 24);
        tabInspect.Name = "tabInspect";
        tabInspect.Padding = new Padding(3);
        tabInspect.Size = new Size(1148, 646);
        tabInspect.Text = "Inspect Seed";
        tabInspect.UseVisualStyleBackColor = true;
        btnInspect.Location = new Point(917, 18);
        btnInspect.Name = "btnInspect";
        btnInspect.Size = new Size(210, 28);
        btnInspect.Text = "Inspect";
        btnInspect.UseVisualStyleBackColor = true;
        btnInspect.Click += btnInspect_Click;
        txtInspectOutput.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        txtInspectOutput.Font = new Font("Consolas", 9F);
        txtInspectOutput.Location = new Point(20, 60);
        txtInspectOutput.Multiline = true;
        txtInspectOutput.Name = "txtInspectOutput";
        txtInspectOutput.ScrollBars = ScrollBars.Both;
        txtInspectOutput.Size = new Size(1107, 566);
        txtInspectOutput.WordWrap = false;
        numInspectSeed.Location = new Point(713, 22);
        numInspectSeed.Maximum = new decimal(new int[] { 99999999, 0, 0, 0 });
        numInspectSeed.Name = "numInspectSeed";
        numInspectSeed.Size = new Size(180, 23);
        labelInspectSeed.AutoSize = true;
        labelInspectSeed.Location = new Point(675, 24);
        labelInspectSeed.Name = "labelInspectSeed";
        labelInspectSeed.Size = new Size(32, 15);
        labelInspectSeed.Text = "Seed";
        cmbInspectMoon.FormattingEnabled = true;
        cmbInspectMoon.Location = new Point(396, 22);
        cmbInspectMoon.Name = "cmbInspectMoon";
        cmbInspectMoon.Size = new Size(249, 23);
        cmbInspectMoon.DropDownStyle = ComboBoxStyle.DropDownList;
        labelInspectMoon.AutoSize = true;
        labelInspectMoon.Location = new Point(357, 25);
        labelInspectMoon.Name = "labelInspectMoon";
        labelInspectMoon.Size = new Size(39, 15);
        labelInspectMoon.Text = "Moon";
        txtInspectVersion.Location = new Point(71, 22);
        txtInspectVersion.Name = "txtInspectVersion";
        txtInspectVersion.Size = new Size(249, 23);
        txtInspectVersion.Text = "decompiled-current";
        labelInspectVersion.AutoSize = true;
        labelInspectVersion.Location = new Point(20, 25);
        labelInspectVersion.Name = "labelInspectVersion";
        labelInspectVersion.Size = new Size(45, 15);
        labelInspectVersion.Text = "Version";
        tabSearch.Controls.Add(btnSearch);
        tabSearch.Controls.Add(txtSearchOutput);
        tabSearch.Controls.Add(txtSearchQuery);
        tabSearch.Controls.Add(labelSearchQuery);
        tabSearch.Controls.Add(numSearchEnd);
        tabSearch.Controls.Add(labelSearchEnd);
        tabSearch.Controls.Add(numSearchStart);
        tabSearch.Controls.Add(labelSearchStart);
        tabSearch.Controls.Add(cmbSearchMoon);
        tabSearch.Controls.Add(labelSearchMoon);
        tabSearch.Controls.Add(txtSearchVersion);
        tabSearch.Controls.Add(labelSearchVersion);
        tabSearch.Location = new Point(4, 24);
        tabSearch.Name = "tabSearch";
        tabSearch.Padding = new Padding(3);
        tabSearch.Size = new Size(1148, 646);
        tabSearch.Text = "Search Range";
        tabSearch.UseVisualStyleBackColor = true;
        btnSearch.Location = new Point(936, 18);
        btnSearch.Name = "btnSearch";
        btnSearch.Size = new Size(191, 28);
        btnSearch.Text = "Search";
        btnSearch.UseVisualStyleBackColor = true;
        btnSearch.Click += btnSearch_Click;
        txtSearchOutput.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        txtSearchOutput.Font = new Font("Consolas", 9F);
        txtSearchOutput.Location = new Point(20, 89);
        txtSearchOutput.Multiline = true;
        txtSearchOutput.Name = "txtSearchOutput";
        txtSearchOutput.ScrollBars = ScrollBars.Both;
        txtSearchOutput.Size = new Size(1107, 537);
        txtSearchOutput.WordWrap = false;
        txtSearchQuery.Location = new Point(71, 53);
        txtSearchQuery.Name = "txtSearchQuery";
        txtSearchQuery.Size = new Size(822, 23);
        txtSearchQuery.Text = "only-goldbar-day";
        labelSearchQuery.AutoSize = true;
        labelSearchQuery.Location = new Point(20, 56);
        labelSearchQuery.Name = "labelSearchQuery";
        labelSearchQuery.Size = new Size(39, 15);
        labelSearchQuery.Text = "Query";
        numSearchEnd.Location = new Point(713, 22);
        numSearchEnd.Maximum = new decimal(new int[] { 99999999, 0, 0, 0 });
        numSearchEnd.Name = "numSearchEnd";
        numSearchEnd.Size = new Size(180, 23);
        numSearchEnd.Value = new decimal(new int[] { 5000, 0, 0, 0 });
        labelSearchEnd.AutoSize = true;
        labelSearchEnd.Location = new Point(685, 24);
        labelSearchEnd.Name = "labelSearchEnd";
        labelSearchEnd.Size = new Size(22, 15);
        labelSearchEnd.Text = "To";
        numSearchStart.Location = new Point(536, 22);
        numSearchStart.Maximum = new decimal(new int[] { 99999999, 0, 0, 0 });
        numSearchStart.Name = "numSearchStart";
        numSearchStart.Size = new Size(120, 23);
        labelSearchStart.AutoSize = true;
        labelSearchStart.Location = new Point(500, 24);
        labelSearchStart.Name = "labelSearchStart";
        labelSearchStart.Size = new Size(30, 15);
        labelSearchStart.Text = "From";
        cmbSearchMoon.FormattingEnabled = true;
        cmbSearchMoon.Location = new Point(328, 22);
        cmbSearchMoon.Name = "cmbSearchMoon";
        cmbSearchMoon.Size = new Size(153, 23);
        cmbSearchMoon.DropDownStyle = ComboBoxStyle.DropDownList;
        labelSearchMoon.AutoSize = true;
        labelSearchMoon.Location = new Point(289, 25);
        labelSearchMoon.Name = "labelSearchMoon";
        labelSearchMoon.Size = new Size(39, 15);
        labelSearchMoon.Text = "Moon";
        txtSearchVersion.Location = new Point(71, 22);
        txtSearchVersion.Name = "txtSearchVersion";
        txtSearchVersion.Size = new Size(194, 23);
        txtSearchVersion.Text = "decompiled-current";
        labelSearchVersion.AutoSize = true;
        labelSearchVersion.Location = new Point(20, 25);
        labelSearchVersion.Name = "labelSearchVersion";
        labelSearchVersion.Size = new Size(45, 15);
        labelSearchVersion.Text = "Version";
        tabExport.Controls.Add(chkExportIncludeRollsJson);
        tabExport.Controls.Add(btnCancelExport);
        tabExport.Controls.Add(btnBrowseExport);
        tabExport.Controls.Add(txtExportOutputFile);
        tabExport.Controls.Add(labelExportOutputFile);
        tabExport.Controls.Add(numExportReportInterval);
        tabExport.Controls.Add(labelExportReportInterval);
        tabExport.Controls.Add(btnStartExport);
        tabExport.Controls.Add(txtExportLog);
        tabExport.Controls.Add(numExportEnd);
        tabExport.Controls.Add(labelExportEnd);
        tabExport.Controls.Add(numExportStart);
        tabExport.Controls.Add(labelExportStart);
        tabExport.Controls.Add(cmbExportMoon);
        tabExport.Controls.Add(labelExportMoon);
        tabExport.Controls.Add(txtExportVersion);
        tabExport.Controls.Add(labelExportVersion);
        tabExport.Location = new Point(4, 24);
        tabExport.Name = "tabExport";
        tabExport.Padding = new Padding(3);
        tabExport.Size = new Size(1148, 646);
        tabExport.Text = "Export CSV (Bulk)";
        tabExport.UseVisualStyleBackColor = true;
        chkExportIncludeRollsJson.AutoSize = true;
        chkExportIncludeRollsJson.Location = new Point(842, 58);
        chkExportIncludeRollsJson.Name = "chkExportIncludeRollsJson";
        chkExportIncludeRollsJson.Size = new Size(140, 19);
        chkExportIncludeRollsJson.Text = "Include full rolls JSON";
        chkExportIncludeRollsJson.UseVisualStyleBackColor = true;
        btnCancelExport.Location = new Point(1015, 53);
        btnCancelExport.Name = "btnCancelExport";
        btnCancelExport.Size = new Size(112, 28);
        btnCancelExport.Text = "Cancel Export";
        btnCancelExport.UseVisualStyleBackColor = true;
        btnCancelExport.Click += btnCancelExport_Click;
        btnBrowseExport.Location = new Point(1072, 19);
        btnBrowseExport.Name = "btnBrowseExport";
        btnBrowseExport.Size = new Size(55, 26);
        btnBrowseExport.Text = "...";
        btnBrowseExport.UseVisualStyleBackColor = true;
        btnBrowseExport.Click += btnBrowseExport_Click;
        txtExportOutputFile.Location = new Point(441, 21);
        txtExportOutputFile.Name = "txtExportOutputFile";
        txtExportOutputFile.Size = new Size(625, 23);
        txtExportOutputFile.Text = "LethalSeedSimulator/exports/all_seeds.csv";
        labelExportOutputFile.AutoSize = true;
        labelExportOutputFile.Location = new Point(366, 24);
        labelExportOutputFile.Name = "labelExportOutputFile";
        labelExportOutputFile.Size = new Size(69, 15);
        labelExportOutputFile.Text = "Output CSV";
        numExportReportInterval.Location = new Point(441, 55);
        numExportReportInterval.Maximum = new decimal(new int[] { 100000000, 0, 0, 0 });
        numExportReportInterval.Minimum = new decimal(new int[] { 1000, 0, 0, 0 });
        numExportReportInterval.Name = "numExportReportInterval";
        numExportReportInterval.Size = new Size(141, 23);
        numExportReportInterval.Value = new decimal(new int[] { 1000000, 0, 0, 0 });
        labelExportReportInterval.AutoSize = true;
        labelExportReportInterval.Location = new Point(357, 58);
        labelExportReportInterval.Name = "labelExportReportInterval";
        labelExportReportInterval.Size = new Size(78, 15);
        labelExportReportInterval.Text = "Report every";
        btnStartExport.Location = new Point(1015, 19);
        btnStartExport.Name = "btnStartExport";
        btnStartExport.Size = new Size(112, 28);
        btnStartExport.Text = "Start Export";
        btnStartExport.UseVisualStyleBackColor = true;
        btnStartExport.Click += btnStartExport_Click;
        txtExportLog.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        txtExportLog.Font = new Font("Consolas", 9F);
        txtExportLog.Location = new Point(20, 89);
        txtExportLog.Multiline = true;
        txtExportLog.Name = "txtExportLog";
        txtExportLog.ScrollBars = ScrollBars.Both;
        txtExportLog.Size = new Size(1107, 537);
        txtExportLog.WordWrap = false;
        numExportEnd.Location = new Point(223, 55);
        numExportEnd.Maximum = new decimal(new int[] { 99999999, 0, 0, 0 });
        numExportEnd.Name = "numExportEnd";
        numExportEnd.Size = new Size(120, 23);
        numExportEnd.Value = new decimal(new int[] { 99999999, 0, 0, 0 });
        labelExportEnd.AutoSize = true;
        labelExportEnd.Location = new Point(195, 58);
        labelExportEnd.Name = "labelExportEnd";
        labelExportEnd.Size = new Size(22, 15);
        labelExportEnd.Text = "To";
        numExportStart.Location = new Point(71, 55);
        numExportStart.Maximum = new decimal(new int[] { 99999999, 0, 0, 0 });
        numExportStart.Name = "numExportStart";
        numExportStart.Size = new Size(120, 23);
        labelExportStart.AutoSize = true;
        labelExportStart.Location = new Point(20, 58);
        labelExportStart.Name = "labelExportStart";
        labelExportStart.Size = new Size(30, 15);
        labelExportStart.Text = "From";
        cmbExportMoon.FormattingEnabled = true;
        cmbExportMoon.Location = new Point(223, 21);
        cmbExportMoon.Name = "cmbExportMoon";
        cmbExportMoon.Size = new Size(120, 23);
        cmbExportMoon.DropDownStyle = ComboBoxStyle.DropDownList;
        labelExportMoon.AutoSize = true;
        labelExportMoon.Location = new Point(178, 24);
        labelExportMoon.Name = "labelExportMoon";
        labelExportMoon.Size = new Size(39, 15);
        labelExportMoon.Text = "Moon";
        txtExportVersion.Location = new Point(71, 21);
        txtExportVersion.Name = "txtExportVersion";
        txtExportVersion.Size = new Size(92, 23);
        txtExportVersion.Text = "decompiled-current";
        labelExportVersion.AutoSize = true;
        labelExportVersion.Location = new Point(20, 24);
        labelExportVersion.Name = "labelExportVersion";
        labelExportVersion.Size = new Size(45, 15);
        labelExportVersion.Text = "Version";
        btnExtractRules.Location = new Point(12, 12);
        btnExtractRules.Name = "btnExtractRules";
        btnExtractRules.Size = new Size(214, 28);
        btnExtractRules.Text = "Extract/Refresh rulepack";
        btnExtractRules.UseVisualStyleBackColor = true;
        btnExtractRules.Click += btnExtractRules_Click;
        txtGlobalInfo.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        txtGlobalInfo.Location = new Point(232, 15);
        txtGlobalInfo.Name = "txtGlobalInfo";
        txtGlobalInfo.ReadOnly = true;
        txtGlobalInfo.Size = new Size(936, 23);
        tabMain.ResumeLayout(false);
        tabInspect.ResumeLayout(false);
        tabInspect.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)numInspectSeed).EndInit();
        tabSearch.ResumeLayout(false);
        tabSearch.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)numSearchEnd).EndInit();
        ((System.ComponentModel.ISupportInitialize)numSearchStart).EndInit();
        tabExport.ResumeLayout(false);
        tabExport.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)numExportReportInterval).EndInit();
        ((System.ComponentModel.ISupportInitialize)numExportEnd).EndInit();
        ((System.ComponentModel.ISupportInitialize)numExportStart).EndInit();
        ResumeLayout(false);
        PerformLayout();
    }

    #endregion

    private TabControl tabMain;
    private TabPage tabInspect;
    private Button btnInspect;
    private TextBox txtInspectOutput;
    private NumericUpDown numInspectSeed;
    private Label labelInspectSeed;
    private ComboBox cmbInspectMoon;
    private Label labelInspectMoon;
    private TextBox txtInspectVersion;
    private Label labelInspectVersion;
    private TabPage tabSearch;
    private Button btnSearch;
    private TextBox txtSearchOutput;
    private TextBox txtSearchQuery;
    private Label labelSearchQuery;
    private NumericUpDown numSearchEnd;
    private Label labelSearchEnd;
    private NumericUpDown numSearchStart;
    private Label labelSearchStart;
    private ComboBox cmbSearchMoon;
    private Label labelSearchMoon;
    private TextBox txtSearchVersion;
    private Label labelSearchVersion;
    private TabPage tabExport;
    private Button btnStartExport;
    private TextBox txtExportLog;
    private NumericUpDown numExportEnd;
    private Label labelExportEnd;
    private NumericUpDown numExportStart;
    private Label labelExportStart;
    private ComboBox cmbExportMoon;
    private Label labelExportMoon;
    private TextBox txtExportVersion;
    private Label labelExportVersion;
    private NumericUpDown numExportReportInterval;
    private Label labelExportReportInterval;
    private Label labelExportOutputFile;
    private TextBox txtExportOutputFile;
    private Button btnBrowseExport;
    private Button btnCancelExport;
    private CheckBox chkExportIncludeRollsJson;
    private Button btnExtractRules;
    private TextBox txtGlobalInfo;
}
