namespace LethalSeedSimulator.Gui;

partial class Form1
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code

    private void InitializeComponent()
    {
        tabMain = new TabControl();
        tabInspect = new TabPage();
        btnInspect = new Button();
        txtInspectOutput = new TextBox();
        numInspectSeed = new NumericUpDown();
        numInspectWeatherSeed = new NumericUpDown();
        labelInspectWeatherSeed = new Label();
        labelInspectSeed = new Label();
        cmbInspectMoon = new ComboBox();
        labelInspectMoon = new Label();
        txtInspectVersion = new TextBox();
        labelInspectVersion = new Label();
        tabBulkSimulator = new TabPage();
        btnBulkCancel = new Button();
        numBulkReportInterval = new NumericUpDown();
        labelBulkReportInterval = new Label();
        chkBulkForceResimulate = new CheckBox();
        btnBulkOptions = new Button();
        txtBulkRange = new TextBox();
        labelBulkRange = new Label();
        btnBulkSimulateSelected = new Button();
        btnBulkSimulateAll = new Button();
        btnBulkRefresh = new Button();
        txtBulkLog = new TextBox();
        lvBulkMoons = new ListView();
        colMoon = new ColumnHeader();
        colSimulated = new ColumnHeader();
        colPercent = new ColumnHeader();
        txtBulkVersion = new TextBox();
        labelBulkVersion = new Label();
        tabBulkViewer = new TabPage();
        tabSetup = new TabPage();
        btnViewNext = new Button();
        btnViewPrev = new Button();
        lblViewPage = new Label();
        numViewPageSize = new NumericUpDown();
        labelViewPageSize = new Label();
        txtViewMaxTotal = new TextBox();
        labelViewMaxTotal = new Label();
        txtViewMinTotal = new TextBox();
        labelViewMinTotal = new Label();
        btnViewLoad = new Button();
        cmbViewMoon = new ComboBox();
        labelViewMoon = new Label();
        txtViewVersion = new TextBox();
        labelViewVersion = new Label();
        dgvViewer = new DataGridView();
        colSeed = new DataGridViewTextBoxColumn();
        colTotalScrap = new DataGridViewTextBoxColumn();
        colScrapCount = new DataGridViewTextBoxColumn();
        colWeather = new DataGridViewTextBoxColumn();
        colKeyCount = new DataGridViewTextBoxColumn();
        colFlowTheme = new DataGridViewTextBoxColumn();
        colApparatusValue = new DataGridViewTextBoxColumn();
        btnExtractRules = new Button();
        txtGlobalInfo = new TextBox();
        labelSetupGameRoot = new Label();
        txtSetupGameRoot = new TextBox();
        btnSetupBrowseGameRoot = new Button();
        labelSetupAssetRipper = new Label();
        txtSetupAssetRipper = new TextBox();
        btnSetupBrowseAssetRipper = new Button();
        btnSetupExtract = new Button();
        btnSetupDownloadAssetRipper = new Button();
        lblSetupStatus = new Label();
        progressSetup = new ProgressBar();
        txtSetupLog = new TextBox();
        tabMain.SuspendLayout();
        tabInspect.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)numInspectSeed).BeginInit();
        ((System.ComponentModel.ISupportInitialize)numInspectWeatherSeed).BeginInit();
        tabBulkSimulator.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)numBulkReportInterval).BeginInit();
        tabBulkViewer.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)numViewPageSize).BeginInit();
        ((System.ComponentModel.ISupportInitialize)dgvViewer).BeginInit();
        tabSetup.SuspendLayout();
        this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        ClientSize = new Size(1180, 760);
        Controls.Add(txtGlobalInfo);
        Controls.Add(btnExtractRules);
        Controls.Add(tabMain);
        MinimumSize = new Size(1100, 700);
        Name = "Form1";
        Text = "Lethal Seed Simulator GUI";
        tabMain.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        tabMain.Controls.Add(tabInspect);
        tabMain.Controls.Add(tabBulkSimulator);
        tabMain.Controls.Add(tabBulkViewer);
        tabMain.Controls.Add(tabSetup);
        tabMain.Location = new Point(12, 74);
        tabMain.Name = "tabMain";
        tabMain.SelectedIndex = 0;
        tabMain.Size = new Size(1156, 674);
        tabInspect.Controls.Add(btnInspect);
        tabInspect.Controls.Add(txtInspectOutput);
        tabInspect.Controls.Add(numInspectSeed);
        tabInspect.Controls.Add(numInspectWeatherSeed);
        tabInspect.Controls.Add(labelInspectWeatherSeed);
        tabInspect.Controls.Add(labelInspectSeed);
        tabInspect.Controls.Add(cmbInspectMoon);
        tabInspect.Controls.Add(labelInspectMoon);
        tabInspect.Controls.Add(txtInspectVersion);
        tabInspect.Controls.Add(labelInspectVersion);
        tabInspect.Location = new Point(4, 24);
        tabInspect.Name = "tabInspect";
        tabInspect.Padding = new Padding(3);
        tabInspect.Size = new Size(1148, 646);
        tabInspect.Text = "Inspector";
        tabInspect.UseVisualStyleBackColor = true;
        btnInspect.Location = new Point(1031, 18);
        btnInspect.Name = "btnInspect";
        btnInspect.Size = new Size(96, 28);
        btnInspect.Text = "Inspect";
        btnInspect.UseVisualStyleBackColor = true;
        btnInspect.Click += btnInspect_Click;
        txtInspectOutput.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        txtInspectOutput.Font = new Font("Consolas", 9F);
        txtInspectOutput.Location = new Point(20, 60);
        txtInspectOutput.Multiline = true;
        txtInspectOutput.Name = "txtInspectOutput";
        txtInspectOutput.ScrollBars = ScrollBars.Both;
        txtInspectOutput.Size = new Size(1107, 566);
        txtInspectOutput.WordWrap = false;
        numInspectSeed.Location = new Point(599, 22);
        numInspectSeed.Maximum = new decimal(new int[] { 99999999, 0, 0, 0 });
        numInspectSeed.Name = "numInspectSeed";
        numInspectSeed.Size = new Size(120, 23);
        numInspectWeatherSeed.Location = new Point(873, 22);
        numInspectWeatherSeed.Maximum = new decimal(new int[] { 99999999, 0, 0, 0 });
        numInspectWeatherSeed.Name = "numInspectWeatherSeed";
        numInspectWeatherSeed.Size = new Size(120, 23);
        labelInspectWeatherSeed.AutoSize = true;
        labelInspectWeatherSeed.Location = new Point(731, 24);
        labelInspectWeatherSeed.Name = "labelInspectWeatherSeed";
        labelInspectWeatherSeed.Size = new Size(136, 15);
        labelInspectWeatherSeed.Text = "Weather seed timeline";
        labelInspectSeed.AutoSize = true;
        labelInspectSeed.Location = new Point(561, 24);
        labelInspectSeed.Name = "labelInspectSeed";
        labelInspectSeed.Size = new Size(32, 15);
        labelInspectSeed.Text = "Seed";
        cmbInspectMoon.FormattingEnabled = true;
        cmbInspectMoon.Location = new Point(396, 22);
        cmbInspectMoon.Name = "cmbInspectMoon";
        cmbInspectMoon.Size = new Size(249, 23);
        cmbInspectMoon.DropDownStyle = ComboBoxStyle.DropDownList;
        labelInspectMoon.AutoSize = true;
        labelInspectMoon.Location = new Point(357, 25);
        labelInspectMoon.Name = "labelInspectMoon";
        labelInspectMoon.Size = new Size(39, 15);
        labelInspectMoon.Text = "Moon";
        txtInspectVersion.Location = new Point(71, 22);
        txtInspectVersion.Name = "txtInspectVersion";
        txtInspectVersion.Size = new Size(249, 23);
        txtInspectVersion.Text = "decompiled-current";
        labelInspectVersion.AutoSize = true;
        labelInspectVersion.Location = new Point(20, 25);
        labelInspectVersion.Name = "labelInspectVersion";
        labelInspectVersion.Size = new Size(45, 15);
        labelInspectVersion.Text = "Version";
        tabBulkSimulator.Controls.Add(btnBulkCancel);
        tabBulkSimulator.Controls.Add(numBulkReportInterval);
        tabBulkSimulator.Controls.Add(labelBulkReportInterval);
        tabBulkSimulator.Controls.Add(chkBulkForceResimulate);
        tabBulkSimulator.Controls.Add(btnBulkOptions);
        tabBulkSimulator.Controls.Add(txtBulkRange);
        tabBulkSimulator.Controls.Add(labelBulkRange);
        tabBulkSimulator.Controls.Add(btnBulkSimulateSelected);
        tabBulkSimulator.Controls.Add(btnBulkSimulateAll);
        tabBulkSimulator.Controls.Add(btnBulkRefresh);
        tabBulkSimulator.Controls.Add(txtBulkLog);
        tabBulkSimulator.Controls.Add(lvBulkMoons);
        tabBulkSimulator.Controls.Add(txtBulkVersion);
        tabBulkSimulator.Controls.Add(labelBulkVersion);
        tabBulkSimulator.Location = new Point(4, 24);
        tabBulkSimulator.Name = "tabBulkSimulator";
        tabBulkSimulator.Padding = new Padding(3);
        tabBulkSimulator.Size = new Size(1148, 646);
        tabBulkSimulator.Text = "Bulk Simulator";
        tabBulkSimulator.UseVisualStyleBackColor = true;
        btnBulkCancel.Location = new Point(1015, 52);
        btnBulkCancel.Name = "btnBulkCancel";
        btnBulkCancel.Size = new Size(112, 28);
        btnBulkCancel.Text = "Cancel";
        btnBulkCancel.UseVisualStyleBackColor = true;
        btnBulkCancel.Click += btnBulkCancel_Click;
        numBulkReportInterval.Location = new Point(576, 56);
        numBulkReportInterval.Maximum = new decimal(new int[] { 100000000, 0, 0, 0 });
        numBulkReportInterval.Minimum = new decimal(new int[] { 1000, 0, 0, 0 });
        numBulkReportInterval.Name = "numBulkReportInterval";
        numBulkReportInterval.Size = new Size(120, 23);
        numBulkReportInterval.Value = new decimal(new int[] { 100000, 0, 0, 0 });
        labelBulkReportInterval.AutoSize = true;
        labelBulkReportInterval.Location = new Point(476, 59);
        labelBulkReportInterval.Name = "labelBulkReportInterval";
        labelBulkReportInterval.Size = new Size(94, 15);
        labelBulkReportInterval.Text = "Report interval";
        chkBulkForceResimulate.AutoSize = true;
        chkBulkForceResimulate.Location = new Point(316, 57);
        chkBulkForceResimulate.Name = "chkBulkForceResimulate";
        chkBulkForceResimulate.Size = new Size(122, 19);
        chkBulkForceResimulate.Text = "Force re-simulate";
        chkBulkForceResimulate.UseVisualStyleBackColor = true;
        btnBulkOptions.Location = new Point(702, 53);
        btnBulkOptions.Name = "btnBulkOptions";
        btnBulkOptions.Size = new Size(100, 28);
        btnBulkOptions.Text = "Options";
        btnBulkOptions.UseVisualStyleBackColor = true;
        btnBulkOptions.Click += btnBulkOptions_Click;
        txtBulkRange.Location = new Point(88, 55);
        txtBulkRange.Name = "txtBulkRange";
        txtBulkRange.ReadOnly = true;
        txtBulkRange.Size = new Size(212, 23);
        labelBulkRange.AutoSize = true;
        labelBulkRange.Location = new Point(20, 58);
        labelBulkRange.Name = "labelBulkRange";
        labelBulkRange.Size = new Size(42, 15);
        labelBulkRange.Text = "Range";
        btnBulkSimulateSelected.Location = new Point(811, 19);
        btnBulkSimulateSelected.Name = "btnBulkSimulateSelected";
        btnBulkSimulateSelected.Size = new Size(155, 28);
        btnBulkSimulateSelected.Text = "Simulate Selected";
        btnBulkSimulateSelected.UseVisualStyleBackColor = true;
        btnBulkSimulateSelected.Click += btnBulkSimulateSelected_Click;
        btnBulkSimulateAll.Location = new Point(972, 19);
        btnBulkSimulateAll.Name = "btnBulkSimulateAll";
        btnBulkSimulateAll.Size = new Size(155, 28);
        btnBulkSimulateAll.Text = "Simulate 100,000,000";
        btnBulkSimulateAll.UseVisualStyleBackColor = true;
        btnBulkSimulateAll.Click += btnBulkSimulateAll_Click;
        btnBulkRefresh.Location = new Point(702, 19);
        btnBulkRefresh.Name = "btnBulkRefresh";
        btnBulkRefresh.Size = new Size(100, 28);
        btnBulkRefresh.Text = "Refresh";
        btnBulkRefresh.UseVisualStyleBackColor = true;
        btnBulkRefresh.Click += btnBulkRefresh_Click;
        txtBulkLog.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        txtBulkLog.Font = new Font("Consolas", 9F);
        txtBulkLog.Location = new Point(20, 412);
        txtBulkLog.Multiline = true;
        txtBulkLog.Name = "txtBulkLog";
        txtBulkLog.ScrollBars = ScrollBars.Both;
        txtBulkLog.Size = new Size(1107, 214);
        txtBulkLog.WordWrap = false;
        lvBulkMoons.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        lvBulkMoons.Columns.AddRange(new ColumnHeader[] { colMoon, colSimulated, colPercent });
        lvBulkMoons.FullRowSelect = true;
        lvBulkMoons.GridLines = true;
        lvBulkMoons.Location = new Point(20, 90);
        lvBulkMoons.MultiSelect = false;
        lvBulkMoons.Name = "lvBulkMoons";
        lvBulkMoons.Size = new Size(1107, 308);
        lvBulkMoons.View = View.Details;
        colMoon.Text = "Moon";
        colMoon.Width = 500;
        colSimulated.Text = "Simulated Seeds";
        colSimulated.Width = 220;
        colPercent.Text = "Progress";
        colPercent.Width = 180;
        txtBulkVersion.Location = new Point(88, 22);
        txtBulkVersion.Name = "txtBulkVersion";
        txtBulkVersion.Size = new Size(212, 23);
        txtBulkVersion.Text = "decompiled-current";
        labelBulkVersion.AutoSize = true;
        labelBulkVersion.Location = new Point(20, 25);
        labelBulkVersion.Name = "labelBulkVersion";
        labelBulkVersion.Size = new Size(45, 15);
        labelBulkVersion.Text = "Version";
        tabBulkViewer.Controls.Add(btnViewNext);
        tabBulkViewer.Controls.Add(btnViewPrev);
        tabBulkViewer.Controls.Add(lblViewPage);
        tabBulkViewer.Controls.Add(numViewPageSize);
        tabBulkViewer.Controls.Add(labelViewPageSize);
        tabBulkViewer.Controls.Add(txtViewMaxTotal);
        tabBulkViewer.Controls.Add(labelViewMaxTotal);
        tabBulkViewer.Controls.Add(txtViewMinTotal);
        tabBulkViewer.Controls.Add(labelViewMinTotal);
        tabBulkViewer.Controls.Add(btnViewLoad);
        tabBulkViewer.Controls.Add(cmbViewMoon);
        tabBulkViewer.Controls.Add(labelViewMoon);
        tabBulkViewer.Controls.Add(txtViewVersion);
        tabBulkViewer.Controls.Add(labelViewVersion);
        tabBulkViewer.Controls.Add(dgvViewer);
        tabBulkViewer.Location = new Point(4, 24);
        tabBulkViewer.Name = "tabBulkViewer";
        tabBulkViewer.Padding = new Padding(3);
        tabBulkViewer.Size = new Size(1148, 646);
        tabBulkViewer.Text = "Bulk Viewer";
        tabBulkViewer.UseVisualStyleBackColor = true;
        btnViewNext.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
        btnViewNext.Location = new Point(1047, 601);
        btnViewNext.Name = "btnViewNext";
        btnViewNext.Size = new Size(80, 28);
        btnViewNext.Text = "Next";
        btnViewNext.UseVisualStyleBackColor = true;
        btnViewNext.Click += btnViewNext_Click;
        btnViewPrev.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
        btnViewPrev.Location = new Point(961, 601);
        btnViewPrev.Name = "btnViewPrev";
        btnViewPrev.Size = new Size(80, 28);
        btnViewPrev.Text = "Prev";
        btnViewPrev.UseVisualStyleBackColor = true;
        btnViewPrev.Click += btnViewPrev_Click;
        lblViewPage.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
        lblViewPage.AutoSize = true;
        lblViewPage.Location = new Point(20, 608);
        lblViewPage.Name = "lblViewPage";
        lblViewPage.Size = new Size(87, 15);
        lblViewPage.Text = "Page 1 / 1 (0 rows)";
        numViewPageSize.Location = new Point(1007, 21);
        numViewPageSize.Maximum = new decimal(new int[] { 5000, 0, 0, 0 });
        numViewPageSize.Minimum = new decimal(new int[] { 10, 0, 0, 0 });
        numViewPageSize.Name = "numViewPageSize";
        numViewPageSize.Size = new Size(120, 23);
        numViewPageSize.Value = new decimal(new int[] { 200, 0, 0, 0 });
        labelViewPageSize.AutoSize = true;
        labelViewPageSize.Location = new Point(944, 24);
        labelViewPageSize.Name = "labelViewPageSize";
        labelViewPageSize.Size = new Size(57, 15);
        labelViewPageSize.Text = "Page size";
        txtViewMaxTotal.Location = new Point(834, 21);
        txtViewMaxTotal.Name = "txtViewMaxTotal";
        txtViewMaxTotal.Size = new Size(100, 23);
        labelViewMaxTotal.AutoSize = true;
        labelViewMaxTotal.Location = new Point(794, 24);
        labelViewMaxTotal.Name = "labelViewMaxTotal";
        labelViewMaxTotal.Size = new Size(34, 15);
        labelViewMaxTotal.Text = "Max";
        txtViewMinTotal.Location = new Point(688, 21);
        txtViewMinTotal.Name = "txtViewMinTotal";
        txtViewMinTotal.Size = new Size(100, 23);
        labelViewMinTotal.AutoSize = true;
        labelViewMinTotal.Location = new Point(651, 24);
        labelViewMinTotal.Name = "labelViewMinTotal";
        labelViewMinTotal.Size = new Size(30, 15);
        labelViewMinTotal.Text = "Min";
        btnViewLoad.Location = new Point(578, 18);
        btnViewLoad.Name = "btnViewLoad";
        btnViewLoad.Size = new Size(65, 28);
        btnViewLoad.Text = "Load";
        btnViewLoad.UseVisualStyleBackColor = true;
        btnViewLoad.Click += btnViewLoad_Click;
        cmbViewMoon.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbViewMoon.FormattingEnabled = true;
        cmbViewMoon.Location = new Point(317, 22);
        cmbViewMoon.Name = "cmbViewMoon";
        cmbViewMoon.Size = new Size(255, 23);
        labelViewMoon.AutoSize = true;
        labelViewMoon.Location = new Point(272, 25);
        labelViewMoon.Name = "labelViewMoon";
        labelViewMoon.Size = new Size(39, 15);
        labelViewMoon.Text = "Moon";
        txtViewVersion.Location = new Point(71, 22);
        txtViewVersion.Name = "txtViewVersion";
        txtViewVersion.Size = new Size(194, 23);
        txtViewVersion.Text = "decompiled-current";
        labelViewVersion.AutoSize = true;
        labelViewVersion.Location = new Point(20, 25);
        labelViewVersion.Name = "labelViewVersion";
        labelViewVersion.Size = new Size(45, 15);
        labelViewVersion.Text = "Version";
        dgvViewer.AllowUserToAddRows = false;
        dgvViewer.AllowUserToDeleteRows = false;
        dgvViewer.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        dgvViewer.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvViewer.Columns.AddRange(new DataGridViewColumn[] { colSeed, colTotalScrap, colScrapCount, colWeather, colKeyCount, colFlowTheme, colApparatusValue });
        dgvViewer.Location = new Point(20, 56);
        dgvViewer.Name = "dgvViewer";
        dgvViewer.ReadOnly = true;
        dgvViewer.RowTemplate.Height = 25;
        dgvViewer.Size = new Size(1107, 534);
        dgvViewer.ColumnHeaderMouseClick += dgvViewer_ColumnHeaderMouseClick;
        colSeed.HeaderText = "Seed";
        colSeed.Name = "seed";
        colSeed.ReadOnly = true;
        colTotalScrap.HeaderText = "Total Scrap";
        colTotalScrap.Name = "total_scrap_value";
        colTotalScrap.ReadOnly = true;
        colScrapCount.HeaderText = "Scrap Count";
        colScrapCount.Name = "scrap_count";
        colScrapCount.ReadOnly = true;
        colWeather.HeaderText = "Weather";
        colWeather.Name = "weather";
        colWeather.ReadOnly = true;
        colKeyCount.HeaderText = "Keys";
        colKeyCount.Name = "key_count";
        colKeyCount.ReadOnly = true;
        colFlowTheme.HeaderText = "Flow Theme";
        colFlowTheme.Name = "dungeon_flow_theme";
        colFlowTheme.ReadOnly = true;
        colApparatusValue.HeaderText = "Apparatus Value";
        colApparatusValue.Name = "apparatus_value";
        colApparatusValue.ReadOnly = true;
        tabSetup.Controls.Add(btnSetupExtract);
        tabSetup.Controls.Add(btnSetupDownloadAssetRipper);
        tabSetup.Controls.Add(lblSetupStatus);
        tabSetup.Controls.Add(progressSetup);
        tabSetup.Controls.Add(btnSetupBrowseAssetRipper);
        tabSetup.Controls.Add(txtSetupAssetRipper);
        tabSetup.Controls.Add(labelSetupAssetRipper);
        tabSetup.Controls.Add(btnSetupBrowseGameRoot);
        tabSetup.Controls.Add(txtSetupGameRoot);
        tabSetup.Controls.Add(labelSetupGameRoot);
        tabSetup.Controls.Add(txtSetupLog);
        tabSetup.Location = new Point(4, 24);
        tabSetup.Name = "tabSetup";
        tabSetup.Padding = new Padding(3);
        tabSetup.Size = new Size(1148, 646);
        tabSetup.Text = "Setup";
        tabSetup.UseVisualStyleBackColor = true;
        labelSetupGameRoot.AutoSize = true;
        labelSetupGameRoot.Location = new Point(20, 25);
        labelSetupGameRoot.Name = "labelSetupGameRoot";
        labelSetupGameRoot.Size = new Size(132, 15);
        labelSetupGameRoot.Text = "Game root (EXE folder)";
        txtSetupGameRoot.Location = new Point(158, 22);
        txtSetupGameRoot.Name = "txtSetupGameRoot";
        txtSetupGameRoot.Size = new Size(900, 23);
        btnSetupBrowseGameRoot.Location = new Point(1066, 20);
        btnSetupBrowseGameRoot.Name = "btnSetupBrowseGameRoot";
        btnSetupBrowseGameRoot.Size = new Size(61, 26);
        btnSetupBrowseGameRoot.Text = "...";
        btnSetupBrowseGameRoot.UseVisualStyleBackColor = true;
        btnSetupBrowseGameRoot.Click += btnSetupBrowseGameRoot_Click;
        labelSetupAssetRipper.AutoSize = true;
        labelSetupAssetRipper.Location = new Point(20, 58);
        labelSetupAssetRipper.Name = "labelSetupAssetRipper";
        labelSetupAssetRipper.Size = new Size(126, 15);
        labelSetupAssetRipper.Text = "AssetRipper CLI path";
        txtSetupAssetRipper.Location = new Point(158, 55);
        txtSetupAssetRipper.Name = "txtSetupAssetRipper";
        txtSetupAssetRipper.Size = new Size(900, 23);
        btnSetupBrowseAssetRipper.Location = new Point(1066, 53);
        btnSetupBrowseAssetRipper.Name = "btnSetupBrowseAssetRipper";
        btnSetupBrowseAssetRipper.Size = new Size(61, 26);
        btnSetupBrowseAssetRipper.Text = "...";
        btnSetupBrowseAssetRipper.UseVisualStyleBackColor = true;
        btnSetupBrowseAssetRipper.Click += btnSetupBrowseAssetRipper_Click;
        btnSetupExtract.Location = new Point(948, 86);
        btnSetupExtract.Name = "btnSetupExtract";
        btnSetupExtract.Size = new Size(179, 28);
        btnSetupExtract.Text = "Extract Needed Data";
        btnSetupExtract.UseVisualStyleBackColor = true;
        btnSetupExtract.Click += btnSetupExtract_Click;
        btnSetupDownloadAssetRipper.Location = new Point(783, 86);
        btnSetupDownloadAssetRipper.Name = "btnSetupDownloadAssetRipper";
        btnSetupDownloadAssetRipper.Size = new Size(159, 28);
        btnSetupDownloadAssetRipper.Text = "Download AssetRipper";
        btnSetupDownloadAssetRipper.UseVisualStyleBackColor = true;
        btnSetupDownloadAssetRipper.Click += btnSetupDownloadAssetRipper_Click;
        lblSetupStatus.AutoSize = true;
        lblSetupStatus.Location = new Point(20, 94);
        lblSetupStatus.Name = "lblSetupStatus";
        lblSetupStatus.Size = new Size(67, 15);
        lblSetupStatus.Text = "Idle (0.0%)";
        progressSetup.Location = new Point(158, 90);
        progressSetup.Maximum = 1000;
        progressSetup.Name = "progressSetup";
        progressSetup.Size = new Size(619, 23);
        txtSetupLog.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        txtSetupLog.Font = new Font("Consolas", 9F);
        txtSetupLog.Location = new Point(20, 120);
        txtSetupLog.Multiline = true;
        txtSetupLog.Name = "txtSetupLog";
        txtSetupLog.ScrollBars = ScrollBars.Both;
        txtSetupLog.Size = new Size(1107, 506);
        txtSetupLog.WordWrap = false;
        btnExtractRules.Location = new Point(12, 12);
        btnExtractRules.Name = "btnExtractRules";
        btnExtractRules.Size = new Size(214, 28);
        btnExtractRules.Text = "Extract/Refresh rulepack";
        btnExtractRules.UseVisualStyleBackColor = true;
        btnExtractRules.Click += btnExtractRules_Click;
        txtGlobalInfo.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        txtGlobalInfo.Location = new Point(232, 15);
        txtGlobalInfo.Name = "txtGlobalInfo";
        txtGlobalInfo.ReadOnly = true;
        txtGlobalInfo.Size = new Size(936, 23);
        tabMain.ResumeLayout(false);
        tabInspect.ResumeLayout(false);
        tabInspect.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)numInspectSeed).EndInit();
        ((System.ComponentModel.ISupportInitialize)numInspectWeatherSeed).EndInit();
        tabBulkSimulator.ResumeLayout(false);
        tabBulkSimulator.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)numBulkReportInterval).EndInit();
        tabBulkViewer.ResumeLayout(false);
        tabBulkViewer.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)numViewPageSize).EndInit();
        ((System.ComponentModel.ISupportInitialize)dgvViewer).EndInit();
        tabSetup.ResumeLayout(false);
        tabSetup.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }

    #endregion

    private TabControl tabMain;
    private TabPage tabInspect;
    private Button btnInspect;
    private TextBox txtInspectOutput;
    private NumericUpDown numInspectSeed;
    private NumericUpDown numInspectWeatherSeed;
    private Label labelInspectWeatherSeed;
    private Label labelInspectSeed;
    private ComboBox cmbInspectMoon;
    private Label labelInspectMoon;
    private TextBox txtInspectVersion;
    private Label labelInspectVersion;
    private TabPage tabBulkSimulator;
    private Button btnBulkCancel;
    private NumericUpDown numBulkReportInterval;
    private Label labelBulkReportInterval;
    private CheckBox chkBulkForceResimulate;
    private Button btnBulkOptions;
    private TextBox txtBulkRange;
    private Label labelBulkRange;
    private Button btnBulkSimulateSelected;
    private Button btnBulkSimulateAll;
    private Button btnBulkRefresh;
    private TextBox txtBulkLog;
    private ListView lvBulkMoons;
    private ColumnHeader colMoon;
    private ColumnHeader colSimulated;
    private ColumnHeader colPercent;
    private TextBox txtBulkVersion;
    private Label labelBulkVersion;
    private TabPage tabBulkViewer;
    private Button btnViewNext;
    private Button btnViewPrev;
    private Label lblViewPage;
    private NumericUpDown numViewPageSize;
    private Label labelViewPageSize;
    private TextBox txtViewMaxTotal;
    private Label labelViewMaxTotal;
    private TextBox txtViewMinTotal;
    private Label labelViewMinTotal;
    private Button btnViewLoad;
    private ComboBox cmbViewMoon;
    private Label labelViewMoon;
    private TextBox txtViewVersion;
    private Label labelViewVersion;
    private DataGridView dgvViewer;
    private DataGridViewTextBoxColumn colSeed;
    private DataGridViewTextBoxColumn colTotalScrap;
    private DataGridViewTextBoxColumn colScrapCount;
    private DataGridViewTextBoxColumn colWeather;
    private DataGridViewTextBoxColumn colKeyCount;
    private DataGridViewTextBoxColumn colFlowTheme;
    private DataGridViewTextBoxColumn colApparatusValue;
    private TabPage tabSetup;
    private Label labelSetupGameRoot;
    private TextBox txtSetupGameRoot;
    private Button btnSetupBrowseGameRoot;
    private Label labelSetupAssetRipper;
    private TextBox txtSetupAssetRipper;
    private Button btnSetupBrowseAssetRipper;
    private Button btnSetupExtract;
    private Button btnSetupDownloadAssetRipper;
    private Label lblSetupStatus;
    private ProgressBar progressSetup;
    private TextBox txtSetupLog;
    private Button btnExtractRules;
    private TextBox txtGlobalInfo;
}
